name: Release to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish'
        required: true
        type: string

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine pytest
          pip install -e .[dev]
      
      - name: Run tests
        run: pytest tests/python
      
      - name: Update version if manual trigger
        if: github.event_name == 'workflow_dispatch'
        run: |
          sed -i "s/version = \".*\"/version = \"${{ inputs.version }}\"/" pyproject.toml
          sed -i "s/version=\".*\"/version=\"${{ inputs.version }}\"/" setup.py
      
      - name: Build package
        run: python -m build
      
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}